mysite/blog/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
app_name = 'blog'

urlpatterns = [
    path('create/',views.create_blog_view, name='create'),
    path('<slug>/',views.detail_blog_view, name='detail'),
    path('<slug>/edit',views.edit_blog_view, name='edit'),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal.urls')),
    path('',include('account.urls')),
    path('blog/',include('blog.urls')),
    path('api/blog/',include('blog.api.urls', 'blog_api')),
    path('api/account/',include('account.api.urls', 'account_api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/personal/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('',views.home_screen_view, name='home'),
]

mysite/personal/models.py
from django.db import models

# Create your models here.

mysite/personal/views.py
from django.shortcuts import render
from blog.models import BlogPost
from operator import attrgetter
from blog.views import get_blog_queryset
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
# Create your views here.

BLOG_POSTS_PER_PAGE = 2

def home_screen_view(request):
    context = {}

    query = ''
    if request.GET:
        query = request.GET.get('q','')
        context['query'] = str(query)

    blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'),reverse=True)
    context['blog_posts'] = blog_posts


    #Pagination
    page = request.GET.get('page', 1)
    blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)
    try:
        blog_posts = blog_posts_paginator.page(page)
    except PageNotAnInteger:
        blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
    except EmptyPage:
        blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

    context['blog_posts'] = blog_posts
    return render(request, 'snippets/home.html', context)

mysite/personal/templates/snippets/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>


<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static '332432_1_org_258071_1_org_image_6ce585b4e6fa432c.jpg' %}" width="72" height="72">
					<p class="lead">In this you can create a New blog post</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

		<!-- Pagination -->
		{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}
		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static '332432_1_org_258071_1_org_image_6ce585b4e6fa432c.jpg' %}" width="72" height="72">
				<p class="lead">In this you can create a New blog post<p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->



	</div>
</div>

{% endblock content %}